apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  namespace: applications
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: applications
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: jenkins-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
